### ISSUE TITLE
[BUG] Noise floor text now red, and color pickers wrong scaling

### ISSUE THREAD

**Issue by RdWing** [ramdor/Thetis#310]
Thetis v2.10.3.4

After installing noticed the noise floor dBm text is now red, the same color as the line, vs yellow as it was before. Instead of having the text be the same color as the line, can we have the text be yellow again?

Also have noticed that when opening all color pickers, they seem to show up in the wrong place (like off screen, or in corners), and are not being properly DPI scaled.

**Comment by ramdor** [comment]
yes text color was changed to be the same as the line as it was fixed at yellow before. There is an option to change the line colour, which also changes the text colour.

No idea about your colour picker issues. All fine here.

![image](https://github.com/ramdor/Thetis/assets/3124967/f2c5fca7-c7b9-4335-9ac2-d489c986198a)

**Comment by ramdor** [comment]
added new colour option for the text

![image](https://github.com/ramdor/Thetis/assets/3124967/71fc6be5-6a4b-4f5c-836d-7936b3cf288a)

**Comment by RdWing** [comment]
Hi, sorry for the late reply. I am still experiencing some strangeness with the color pickers. On the latest 2.10.3.5 PR3, I can't seem to get the pickers to appear at all anymore.
https://youtu.be/ua2w4MbsP9M

**Comment by ramdor** [comment]
no changes to ColorButton.cs or ColorButton.resx for 7 years. Very odd indeed.

**Comment by ramdor** [comment]
can you check ErrorLog.txt (in same folder as database.xml). Also are you using anything which may take the focus away from SetupForm?

**Comment by RdWing** [comment]
Nothing really in ErrorLog.txt, nothing recent at least. I have nothing running that would take the focus away.

I think what's happening is that this is a multi monitor setup. Main display is 3840x1600, 100% scaling. The second monitor is a 4k 2160x3840 in vertical mode, where I have some meters displayed. So something gets a little wonky with that.

I was able to work around the issue by changing some of the scaling options.
![Screenshot 2023-12-10 152937](https://github.com/ramdor/Thetis/assets/19214916/b78cb6ea-dc48-442a-bf98-f587f2ffef63)

**Comment by ramdor** [comment]
interesting, I just tried landscape on my second monitor, but it is the same native res as primary monitor. ColourPicker worked ok. I even tried different display scales and it worked ok. Perhaps screen driver needs an update?

Anyway, closing this out. Cheers for tracking down a work around.
